### ISSUE TITLE
installation in the README did not work.

### ISSUE THREAD

**Issue by Zhenglei-BCS** [pharmaR/rvalhub-quarto#3]
![image](https://github.com/pharmaR/rvalhub-quarto/assets/7943721/49d95a8c-fe93-4387-9961-3decb3f9f3b8)

It seems that I should have a local repository to add it. But I am not sure. 

What works for me: 
https://github.com/beatrizmilz/quarto-rladies-theme

**Comment by dgkf** [comment]
Ah, thanks @Zhenglei-BCS! I think the `quarto` cli tool changed some of their commands since I first made this. I'll update it to reflect the current commands.
